##
# @see  https://govcms.gov.au/wiki-advanced#docker
#

ARG GOVCMS_IMAGE_VERSION=11.x-latest

FROM govcms/test:${GOVCMS_IMAGE_VERSION}

ENV WEBROOT=web

COPY themes/ /app/web/themes/custom
COPY config /app/config
COPY favicon.ico /app/web
COPY tests /app/tests/
